# Lifted from: https://github.com/mozilla-services/Dockerflow/blob/master/.circleci/config.yml
#
# These environment variables must be set in CircleCI UI:
#
# DOCKERHUB_REPO - Docker Hub repo, format: <username>/<repo>
# DOCKER_USER    - Docker Hub username
# DOCKER_PASS    - Docker Hub password

version: 2

jobs:
  deploy:
    docker:
      - image: docker:stable-git
    working_directory: /dockerflow
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Create a version.json
          command: |
            # create a version.json per https://github.com/mozilla-services/Dockerflow/blob/master/docs/version_object.md
            printf '{"commit":"%s","version":"%s","source":"https://github.com/%s/%s","build":"%s"}\n' \
            "$CIRCLE_SHA1" \
            "$CIRCLE_TAG" \
            "$CIRCLE_PROJECT_USERNAME" \
            "$CIRCLE_PROJECT_REPONAME" \
            "$CIRCLE_BUILD_URL" > version.json

      - run:
          name: Build Docker image
          command: make build

      - run:
          name: Deploy to Dockerhub
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker tag app:build ${DOCKERHUB_REPO}:latest
            docker push ${DOCKERHUB_REPO}:latest

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
